import type { Metadata } from "next";
import { Cause } from "next/font/google";
import "./globals.css";
import { ToastAlert } from "./_components/ToastAlert";
import { Header } from "./_components/Header";
import { MantineProvider } from "@mantine/core";

const cause = Cause({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cause.className} ${cause.className} antialiased relative min-h-screen flex flex-col bg-[#141C24]`}
      >
        <MantineProvider>{children}</MantineProvider>
        <ToastAlert />
      </body>
    </html>
  );
}
